const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

/**
 * ChainProof Deployment Script
 * ==============================
 * Deploys ActorRegistry first, then CredentialIssuer (passing the registry address).
 * After deployment, writes a deployment manifest (addresses + ABIs) directly to the
 * frontend/src/contracts directory so the Vite app can import them without extra build steps.
 *
 * Usage:
 *   npx hardhat run scripts/deploy.js --network localhost
 *   npx hardhat run scripts/deploy.js --network sepolia
 */

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  const network = hre.network.name;

  console.log("=".repeat(60));
  console.log("  ChainProof Deployment Script");
  console.log("=".repeat(60));
  console.log(`  Network:  ${network}`);
  console.log(`  Deployer: ${deployer.address}`);

  // Fetch deployer balance for pre-flight check
  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log(`  Balance:  ${hre.ethers.formatEther(balance)} ETH`);
  console.log("=".repeat(60));

  // -------------------------------------------------------------------------
  // Step 1: Deploy ActorRegistry (deployer is the initial platform verifier —
  // the address that approves/rejects College and Company registrations)
  // -------------------------------------------------------------------------
  console.log("\n[1/3] Deploying ActorRegistry...");
  const ActorRegistry = await hre.ethers.getContractFactory("ActorRegistry");
  const actorRegistry = await ActorRegistry.deploy(deployer.address);
  await actorRegistry.waitForDeployment();
  const registryAddress = await actorRegistry.getAddress();
  console.log(`      ✓ ActorRegistry deployed at: ${registryAddress}`);
  console.log(`      ✓ Initial verifier: ${deployer.address}`);

  // -------------------------------------------------------------------------
  // Step 2: Deploy CredentialIssuer (passing registry address to constructor)
  // -------------------------------------------------------------------------
  console.log("\n[2/3] Deploying CredentialIssuer...");
  const CredentialIssuer = await hre.ethers.getContractFactory("CredentialIssuer");
  const credentialIssuer = await CredentialIssuer.deploy(registryAddress);
  await credentialIssuer.waitForDeployment();
  const issuerAddress = await credentialIssuer.getAddress();
  console.log(`      ✓ CredentialIssuer deployed at: ${issuerAddress}`);

  // -------------------------------------------------------------------------
  // Step 3: Deploy PlacementTracker (passing registry address to constructor)
  // -------------------------------------------------------------------------
  console.log("\n[3/3] Deploying PlacementTracker...");
  const PlacementTracker = await hre.ethers.getContractFactory("PlacementTracker");
  const placementTracker = await PlacementTracker.deploy(registryAddress);
  await placementTracker.waitForDeployment();
  const trackerAddress = await placementTracker.getAddress();
  console.log(`      ✓ PlacementTracker deployed at: ${trackerAddress}`);

  // -------------------------------------------------------------------------
  // Step 4: Extract ABIs from compiled artifacts
  // -------------------------------------------------------------------------
  const registryArtifact = await hre.artifacts.readArtifact("ActorRegistry");
  const issuerArtifact = await hre.artifacts.readArtifact("CredentialIssuer");
  const trackerArtifact = await hre.artifacts.readArtifact("PlacementTracker");

  // -------------------------------------------------------------------------
  // Step 5: Write deployment manifest to frontend/src/contracts/
  // -------------------------------------------------------------------------
  const contractsDir = path.join(__dirname, "..", "frontend", "src", "contracts");

  // Ensure directory exists (create recursively if needed)
  if (!fs.existsSync(contractsDir)) {
    fs.mkdirSync(contractsDir, { recursive: true });
    console.log(`\n[FS] Created directory: ${contractsDir}`);
  }

  // Build the deployment manifest object
  const deploymentManifest = {
    network: network,
    chainId: hre.network.config.chainId || 31337,
    deployedAt: new Date().toISOString(),
    deployer: deployer.address,
    contracts: {
      ActorRegistry: {
        address: registryAddress,
        abi: registryArtifact.abi,
      },
      CredentialIssuer: {
        address: issuerAddress,
        abi: issuerArtifact.abi,
      },
      PlacementTracker: {
        address: trackerAddress,
        abi: trackerArtifact.abi,
      },
    },
  };

  // Write the manifest as a single importable JS module
  const manifestContent = `// AUTO-GENERATED by scripts/deploy.js — DO NOT EDIT MANUALLY
// Generated: ${new Date().toISOString()}
// Network: ${network}

export const DEPLOYMENT = ${JSON.stringify(deploymentManifest, null, 2)};

export const ACTOR_REGISTRY_ADDRESS = "${registryAddress}";
export const CREDENTIAL_ISSUER_ADDRESS = "${issuerAddress}";
export const PLACEMENT_TRACKER_ADDRESS = "${trackerAddress}";

export const ACTOR_REGISTRY_ABI = ${JSON.stringify(registryArtifact.abi, null, 2)};
export const CREDENTIAL_ISSUER_ABI = ${JSON.stringify(issuerArtifact.abi, null, 2)};
export const PLACEMENT_TRACKER_ABI = ${JSON.stringify(trackerArtifact.abi, null, 2)};
`;

  const manifestPath = path.join(contractsDir, "deployment.js");
  fs.writeFileSync(manifestPath, manifestContent, "utf8");

  console.log("\n[FS] Deployment manifest written to:");
  console.log(`     ${manifestPath}`);

  // -------------------------------------------------------------------------
  // Step 6: Summary
  // -------------------------------------------------------------------------
  console.log("\n" + "=".repeat(60));
  console.log("  Deployment Complete!");
  console.log("=".repeat(60));
  console.log(`  ActorRegistry:     ${registryAddress}`);
  console.log(`  CredentialIssuer:  ${issuerAddress}`);
  console.log(`  PlacementTracker:  ${trackerAddress}`);
  console.log(`  Network:           ${network}`);
  console.log("=".repeat(60));
  console.log("\n  Next Steps:");
  console.log("  1. cd backend && npm run dev   (see backend/.env.example)");
  console.log("  2. cd frontend && npm run dev");
  console.log("  No wallet/MetaMask needed — sign up with email/password in the app.");
  console.log("=".repeat(60) + "\n");
}

// Execute deployment and handle top-level errors gracefully
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("\n[ERROR] Deployment failed:");
    console.error(error);
    process.exit(1);
  });
